from pathlib import Path
import json
import time
import requests
import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

COORDINATES_FILE = (
    PROJECT_ROOT
    / "data"
    / "reference"
    / "district_coordinates.csv"
)

RAW_DIR = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "pvgis"
)

MANIFEST_FILE = (
    RAW_DIR
    / "download_manifest.csv"
)


# ============================================================
# PVGIS CONFIGURATION
# ============================================================

PVGIS_URL = (
    "https://re.jrc.ec.europa.eu/api/v5_3/seriescalc"
)

# Normalized reference system
PEAKPOWER_KWP = 1

# Crystalline silicon
PV_TECHNOLOGY = "crystSi"

# Rooftop/building-mounted system
MOUNTING_PLACE = "building"

# PVGIS standard system losses
SYSTEM_LOSS_PERCENT = 14

# Include radiation components
COMPONENTS = 1

# Return local standard time
LOCAL_TIME = 1

# Ask PVGIS to calculate PV production
PV_CALCULATION = 1

# Automatically use the available PVGIS historical period.
# We intentionally DO NOT hard-code 2024/2025 because
# PVGIS 5.3 documented datasets do not necessarily contain
# those years.
START_YEAR = None
END_YEAR = None

# Request timeout
REQUEST_TIMEOUT = 120

# Wait between requests
REQUEST_DELAY_SECONDS = 1.0

# Retry configuration
MAX_RETRIES = 5


# ============================================================
# FUNCTIONS
# ============================================================

def load_coordinates():
    """
    Load district coordinates generated by Phase 2.1.
    """

    if not COORDINATES_FILE.exists():
        raise FileNotFoundError(
            f"Missing file:\n{COORDINATES_FILE}\n\n"
            "Run Phase 2.1 first."
        )

    df = pd.read_csv(
        COORDINATES_FILE,
        encoding="utf-8"
    )

    required_columns = [
        "district_id",
        "district_name",
        "region_id",
        "region_name",
        "latitude",
        "longitude",
        "coordinate_method",
        "source_points_count",
    ]

    missing = [
        col
        for col in required_columns
        if col not in df.columns
    ]

    if missing:
        raise ValueError(
            "district_coordinates.csv is missing columns: "
            f"{missing}"
        )

    return df


def validate_coordinates(df):
    """
    Validate that every district has a usable coordinate.
    """

    if len(df) != 50:
        raise ValueError(
            f"Expected 50 districts, found {len(df)}."
        )

    if df["district_id"].duplicated().any():
        raise ValueError(
            "Duplicate district IDs detected."
        )

    df["latitude"] = pd.to_numeric(
        df["latitude"],
        errors="coerce"
    )

    df["longitude"] = pd.to_numeric(
        df["longitude"],
        errors="coerce"
    )

    missing = df[
        df["latitude"].isna()
        |
        df["longitude"].isna()
    ]

    if len(missing) > 0:

        print(
            "\nThe following districts do not have coordinates:"
        )

        print(
            missing[
                [
                    "district_id",
                    "district_name",
                ]
            ].to_string(index=False)
        )

        raise ValueError(
            "All 50 districts must have coordinates "
            "before downloading PVGIS data."
        )

    # Tunisia sanity bounds
    invalid = df[
        ~df["latitude"].between(30, 38)
        |
        ~df["longitude"].between(7, 12)
    ]

    if len(invalid) > 0:

        print(
            "\nInvalid Tunisia coordinates:"
        )

        print(
            invalid[
                [
                    "district_id",
                    "district_name",
                    "latitude",
                    "longitude",
                ]
            ].to_string(index=False)
        )

        raise ValueError(
            "One or more district coordinates "
            "are outside Tunisia sanity bounds."
        )

    return df


def build_params(row):
    """
    Build the official PVGIS seriescalc parameters.
    """

    params = {
        "lat": float(row["latitude"]),
        "lon": float(row["longitude"]),

        # PV calculation
        "pvcalculation": PV_CALCULATION,

        # Normalized 1 kWp reference
        "peakpower": PEAKPOWER_KWP,

        # PV technology
        "pvtechchoice": PV_TECHNOLOGY,

        # Rooftop/building
        "mountingplace": MOUNTING_PLACE,

        # System losses
        "loss": SYSTEM_LOSS_PERCENT,

        # Radiation components
        "components": COMPONENTS,

        # Local standard time
        "localtime": LOCAL_TIME,

        # JSON
        "outputformat": "json",
    }

    if START_YEAR is not None:
        params["startyear"] = START_YEAR

    if END_YEAR is not None:
        params["endyear"] = END_YEAR

    return params


def request_pvgis(params):
    """
    Request PVGIS with retries.

    PVGIS can return HTTP 529 when the service is overloaded.
    The official documentation recommends retrying after a delay.
    """

    last_error = None

    for attempt in range(1, MAX_RETRIES + 1):

        try:

            response = requests.get(
                PVGIS_URL,
                params=params,
                timeout=REQUEST_TIMEOUT,
            )

            # Successful request
            if response.status_code == 200:
                return response

            # PVGIS overload
            if response.status_code == 529:

                wait_time = 5 * attempt

                print(
                    f"    PVGIS overloaded (529). "
                    f"Retry {attempt}/{MAX_RETRIES} "
                    f"in {wait_time}s..."
                )

                time.sleep(wait_time)

                continue

            # Other HTTP errors
            response.raise_for_status()

        except requests.RequestException as exc:

            last_error = exc

            wait_time = 5 * attempt

            print(
                f"    Request error: {exc}"
            )

            print(
                f"    Retry {attempt}/{MAX_RETRIES} "
                f"in {wait_time}s..."
            )

            time.sleep(wait_time)

    raise RuntimeError(
        f"PVGIS request failed after "
        f"{MAX_RETRIES} attempts.\n"
        f"Last error: {last_error}"
    )


def validate_pvgis_response(data):
    """
    Basic structural validation of the PVGIS JSON.
    """

    if not isinstance(data, dict):
        raise ValueError(
            "PVGIS response is not a JSON object."
        )

    if "outputs" not in data:
        raise ValueError(
            "PVGIS response does not contain 'outputs'."
        )

    outputs = data["outputs"]

    if "hourly" not in outputs:
        raise ValueError(
            "PVGIS response does not contain "
            "'outputs.hourly'."
        )

    hourly = outputs["hourly"]

    if not isinstance(hourly, list):
        raise ValueError(
            "PVGIS hourly output is not a list."
        )

    if len(hourly) == 0:
        raise ValueError(
            "PVGIS returned zero hourly records."
        )

    # Validate first record
    first = hourly[0]

    if "time" not in first:
        raise ValueError(
            "PVGIS hourly record has no 'time' field."
        )

    if "P" not in first:
        raise ValueError(
            "PVGIS hourly record has no 'P' field."
        )

    return True


def save_json(
    data,
    row,
    output_file,
):
    """
    Save the complete original PVGIS JSON.

    Keeping the original response is important for
    reproducibility and auditing.
    """

    metadata = {
        "project": "Prosol Forecast",
        "phase": "2.2",
        "source": "PVGIS 5.3",
        "api": PVGIS_URL,

        "district_id": int(
            row["district_id"]
        ),

        "district_name": str(
            row["district_name"]
        ),

        "region_id": int(
            row["region_id"]
        ),

        "region_name": str(
            row["region_name"]
        ),

        "latitude": float(
            row["latitude"]
        ),

        "longitude": float(
            row["longitude"]
        ),

        "peakpower_kwp": PEAKPOWER_KWP,

        "pvtechchoice": PV_TECHNOLOGY,

        "mountingplace": MOUNTING_PLACE,

        "loss_percent": SYSTEM_LOSS_PERCENT,

        "components": COMPONENTS,

        "localtime": LOCAL_TIME,
    }

    payload = {
        "request_metadata": metadata,
        "pvgis_response": data,
    }

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            payload,
            file,
            ensure_ascii=False,
            indent=2,
        )


def extract_hourly_count(json_file):
    """
    Read saved PVGIS JSON and count hourly records.
    """

    with open(
        json_file,
        "r",
        encoding="utf-8"
    ) as file:

        payload = json.load(file)

    return len(
        payload[
            "pvgis_response"
        ][
            "outputs"
        ][
            "hourly"
        ]
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)
    print("PHASE 2.2 - DOWNLOAD PVGIS HOURLY DATA")
    print("=" * 70)

    # --------------------------------------------------------
    # Load coordinates
    # --------------------------------------------------------

    print(
        "\n[1/5] Loading district coordinates..."
    )

    df = load_coordinates()

    df = validate_coordinates(df)

    print(
        f"  Valid districts: {len(df)}"
    )

    # --------------------------------------------------------
    # Prepare output
    # --------------------------------------------------------

    print(
        "\n[2/5] Preparing output directory..."
    )

    RAW_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    print(
        f"  Output: {RAW_DIR}"
    )

    # --------------------------------------------------------
    # Existing files
    # --------------------------------------------------------

    existing_files = set(
        path.name
        for path in RAW_DIR.glob(
            "district_*.json"
        )
    )

    print(
        f"  Existing district files: "
        f"{len(existing_files)}"
    )

    # --------------------------------------------------------
    # Download
    # --------------------------------------------------------

    print(
        "\n[3/5] Downloading PVGIS data..."
    )

    print(
        f"  API: {PVGIS_URL}"
    )

    print(
        f"  Peak power: {PEAKPOWER_KWP} kWp"
    )

    print(
        f"  Technology: {PV_TECHNOLOGY}"
    )

    print(
        f"  Mounting: {MOUNTING_PLACE}"
    )

    print(
        f"  Loss: {SYSTEM_LOSS_PERCENT}%"
    )

    print(
        f"  Local time: {LOCAL_TIME}"
    )

    manifest_records = []

    total = len(df)

    for index, row in df.iterrows():

        district_id = int(
            row["district_id"]
        )

        district_name = str(
            row["district_name"]
        ).strip()

        output_file = (
            RAW_DIR
            / f"district_{district_id:02d}.json"
        )

        print(
            f"\n[{index + 1}/{total}] "
            f"{district_id:02d} - {district_name}"
        )

        print(
            f"    Coordinates: "
            f"{row['latitude']}, "
            f"{row['longitude']}"
        )

        # ----------------------------------------------------
        # Resume support
        # ----------------------------------------------------

        if output_file.exists():

            try:

                hourly_count = (
                    extract_hourly_count(
                        output_file
                    )
                )

                print(
                    f"    Already downloaded: "
                    f"{hourly_count:,} hourly records"
                )

                manifest_records.append({

                    "district_id": district_id,

                    "district_name": district_name,

                    "region_id": int(
                        row["region_id"]
                    ),

                    "region_name": str(
                        row["region_name"]
                    ),

                    "latitude": float(
                        row["latitude"]
                    ),

                    "longitude": float(
                        row["longitude"]
                    ),

                    "status": "SKIPPED_EXISTING",

                    "hourly_records": hourly_count,

                    "file": output_file.name,

                })

                continue

            except Exception:

                print(
                    "    Existing file is invalid. "
                    "Downloading again..."
                )

        # ----------------------------------------------------
        # Build request
        # ----------------------------------------------------

        params = build_params(row)

        try:

            response = request_pvgis(
                params
            )

            data = response.json()

            validate_pvgis_response(
                data
            )

            # ------------------------------------------------
            # Save original JSON
            # ------------------------------------------------

            save_json(
                data,
                row,
                output_file,
            )

            hourly_count = len(
                data[
                    "outputs"
                ][
                    "hourly"
                ]
            )

            print(
                f"    SUCCESS: "
                f"{hourly_count:,} hourly records"
            )

            manifest_records.append({

                "district_id": district_id,

                "district_name": district_name,

                "region_id": int(
                    row["region_id"]
                ),

                "region_name": str(
                    row["region_name"]
                ),

                "latitude": float(
                    row["latitude"]
                ),

                "longitude": float(
                    row["longitude"]
                ),

                "status": "DOWNLOADED",

                "hourly_records": hourly_count,

                "file": output_file.name,

            })

        except Exception as exc:

            print(
                f"    ERROR: {exc}"
            )

            manifest_records.append({

                "district_id": district_id,

                "district_name": district_name,

                "region_id": int(
                    row["region_id"]
                ),

                "region_name": str(
                    row["region_name"]
                ),

                "latitude": float(
                    row["latitude"]
                ),

                "longitude": float(
                    row["longitude"]
                ),

                "status": "ERROR",

                "hourly_records": 0,

                "file": output_file.name,

            })

        # ----------------------------------------------------
        # Avoid hammering PVGIS
        # ----------------------------------------------------

        time.sleep(
            REQUEST_DELAY_SECONDS
        )

    # --------------------------------------------------------
    # Save manifest
    # --------------------------------------------------------

    print(
        "\n[4/5] Saving download manifest..."
    )

    manifest = pd.DataFrame(
        manifest_records
    )

    manifest.to_csv(
        MANIFEST_FILE,
        index=False,
        encoding="utf-8"
    )

    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print(
        "\n[5/5] Final summary..."
    )

    downloaded = (
        manifest["status"]
        .isin(
            [
                "DOWNLOADED",
                "SKIPPED_EXISTING",
            ]
        )
        .sum()
    )

    errors = (
        manifest["status"]
        == "ERROR"
    ).sum()

    total_hours = (
        pd.to_numeric(
            manifest["hourly_records"],
            errors="coerce"
        )
        .fillna(0)
        .sum()
    )

    print(
        f"\n  Districts processed : {len(manifest)}"
    )

    print(
        f"  Successful           : {downloaded}"
    )

    print(
        f"  Errors               : {errors}"
    )

    print(
        f"  Total hourly records : "
        f"{int(total_hours):,}"
    )

    print(
        f"\n  Raw files:"
    )

    print(
        f"  {RAW_DIR}"
    )

    print(
        f"\n  Manifest:"
    )

    print(
        f"  {MANIFEST_FILE}"
    )

    if errors > 0:

        print(
            "\nWARNING:"
        )

        print(
            "Some districts failed. "
            "Run the script again; existing successful "
            "files will be skipped."
        )

    else:

        print(
            "\nPHASE 2.2 DOWNLOAD COMPLETE."
        )


if __name__ == "__main__":
    main()